language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "7.2.1"
before_script: yarn add react@^16.0.0 react-dom@^16.0.0 --peer
after_success: yarn run coverage
after_script: chmod 400 key.pem ; scp -o StrictHostKeyChecking=no -i key.pem example/ root@137.135.113.29:/tmp/test ; yarn run coveralls 
script:
  - npm run build
on:
  branch: master
